import { Link } from 'react-router-dom'
import { BatteryCharging, Boxes, BrainCircuit, ChevronRight, CircleDot, Drone, PackageCheck, Pill, Route } from 'lucide-react'
import { useApp } from '../appStore'
import MetricCard from '../components/common/MetricCard'
import Notice from '../components/common/Notice'

const flow = [['Flood demand data', CircleDot], ['PSO planning', Boxes], ['Initial allocation', PackageCheck], ['Drone environment', Route], ['VI & Q-Learning', BrainCircuit], ['Comparison', ChevronRight]]
export default function Dashboard() {
  const { villages, resources, results } = useApp()
  return <div><section className="relative overflow-hidden rounded-3xl bg-[#123840] px-6 py-8 text-white md:px-10 md:py-12"><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-teal-400/10"/><p className="text-xs font-bold uppercase tracking-[.22em] text-teal-300">Bangladesh flood relief · AI laboratory</p><h1 className="mt-3 max-w-3xl text-3xl font-bold leading-tight md:text-5xl">Intelligent supply planning for flood-isolated communities</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-300 md:text-base">Explore how Particle Swarm Optimization allocates scarce relief and how two decision algorithms navigate uncertainty in one scientifically shared drone environment.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/pso" className="btn-primary !bg-teal-500 hover:!bg-teal-400">Run PSO experiment <ChevronRight size={17}/></Link><Link to="/environment" className="btn-secondary !border-white/20 !bg-white/10 !text-white">Open simulation</Link></div></section>
  <div className="mt-5"><Notice>Chattogram locality names and flood context are web-sourced. Populations shown here, relief demands, area points, weather transitions, and algorithm results are simulated. This is not an operational response system or medical advice.</Notice></div>
  <section className="mt-7"><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow">Available resources</p><h2 className="mt-1 text-xl font-bold">Relief hub inventory</h2></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Food packages" value={resources.food} detail="Ready for allocation" icon={PackageCheck}/><MetricCard label="Medicine" value={resources.medicine} detail="Priority cargo" icon={Pill} tone="rose"/><MetricCard label="Active drones" value={resources.drones} detail={`${resources.maxRange} km maximum range`} icon={Drone} tone="blue"/><MetricCard label="Battery packs" value={resources.batteries} detail={`${resources.batteryCapacity} charge units per drone`} icon={BatteryCharging} tone="amber"/></div></section>
  <section className="mt-7"><p className="eyebrow">Affected communities</p><h2 className="mt-1 text-xl font-bold">Village demand overview</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{villages.map((v) => <article key={v.id} className="panel-pad"><div className="flex items-center justify-between"><span className="rounded-lg bg-teal-50 px-2.5 py-1 text-xs font-bold text-teal-700">{v.id}</span><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${v.urgency === 'Critical' ? 'bg-rose-100 text-rose-700' : v.urgency === 'High' ? 'bg-orange-100 text-orange-700' : 'bg-amber-100 text-amber-700'}`}>{v.urgency}</span></div><h3 className="mt-4 font-bold text-slate-900">{v.name}</h3><p className="mt-1 text-xs text-slate-500">{v.population} people · {v.distance} km from hub</p><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><div className="rounded-xl bg-slate-50 p-3"><span className="block text-xs text-slate-500">Food</span><strong>{v.foodDemand}</strong></div><div className="rounded-xl bg-slate-50 p-3"><span className="block text-xs text-slate-500">Medicine</span><strong>{v.medicineDemand}</strong></div></div></article>)}</div></section>
  <section className="mt-7 grid gap-4 lg:grid-cols-3"><MetricCard label="PSO best cost" value={results.pso ? results.pso.cost.toFixed(1) : 'Not run'} detail="Resource planning" icon={Boxes}/><MetricCard label="Value Iteration success" value={results.vi?.evaluation ? `${results.vi.evaluation.successRate.toFixed(1)}%` : 'Not evaluated'} detail="Model-based policy" icon={BrainCircuit} tone="blue"/><MetricCard label="Q-Learning success" value={results.ql ? `${results.ql.successRate.toFixed(1)}%` : 'Not trained'} detail="Training performance" icon={Drone} tone="amber"/></section>
  <section className="panel-pad mt-7"><p className="eyebrow">End-to-end workflow</p><h2 className="mt-1 text-xl font-bold">From demand to decision</h2><div className="mt-6 grid gap-3 md:grid-cols-6">{flow.map(([label, Icon], i) => <div key={label} className="relative flex items-center gap-3 rounded-xl bg-slate-50 p-3 md:block md:text-center"><span className="inline-flex rounded-xl bg-white p-2 text-teal-700 shadow-sm"><Icon size={18}/></span><p className="mt-2 text-xs font-semibold">{label}</p>{i < flow.length - 1 && <ChevronRight className="absolute -right-4 top-1/2 z-10 hidden -translate-y-1/2 text-slate-300 md:block" size={17}/>}</div>)}</div></section></div>
}
