import { useEffect, useMemo, useRef, useState } from 'react'
import { Pause, Play, RotateCcw, SkipForward } from 'lucide-react'
import PageIntro from '../components/common/PageIntro'
import OpenStreetDroneMap from '../components/simulation/OpenStreetDroneMap'
import { FloodDroneEnvironment } from '../simulation/floodDroneEnvironment'
import { useApp } from '../appStore'
import { chooseSafeMissionAction } from '../simulation/manualPolicy'
import { buildVillageScenario, MAX_DYNAMIC_VILLAGES } from '../simulation/dynamicVillageNetwork'

export default function EnvironmentPage() {
  const { resources, setResources } = useApp()
  const batteryCapacity = resources.batteryCapacity
  const [villageCount,setVillageCount] = useState(4)
  const scenario = useMemo(() => buildVillageScenario(villageCount), [villageCount])
  const envRef = useRef(null)
  if (!envRef.current) envRef.current = new FloodDroneEnvironment({ seed:7, maxBattery:batteryCapacity, villages:scenario.villages, networkGraph:scenario.graph, targets:scenario.targets })
  const [state,setState] = useState(() => envRef.current.reset())
  const [timeline,setTimeline] = useState([]), [running,setRunning] = useState(false), [total,setTotal] = useState(0)
  const [mission,setMission] = useState({ target:'V3-A1',payload:'BOTH',weather:'SAFE' })
  const newEnvironment = () => { envRef.current = new FloodDroneEnvironment({ seed:7, maxBattery:batteryCapacity, villages:scenario.villages, networkGraph:scenario.graph, targets:scenario.targets }); return envRef.current }
  const reset = () => { setRunning(false); const s = newEnvironment().reset(mission); setState(s); setTimeline([]); setTotal(0) }
  const start = () => { const s = newEnvironment().reset(mission); setState(s); setTimeline([]); setTotal(0); setRunning(true) }
  const step = () => { if (state.terminal) return setRunning(false); const action = chooseSafeMissionAction(state,scenario.graph), from = state, result = envRef.current.step(action); setState(result.state); setTotal((t) => t + result.reward); setTimeline((rows) => [...rows,{ step: rows.length + 1, from: envRef.current.encodeState(from), action, to: envRef.current.encodeState(result.state), reward: result.reward, event: result.event }]); if (result.done) setRunning(false) }
  useEffect(() => { if (!running) return; const timer = setTimeout(step, 650); return () => clearTimeout(timer) })
  useEffect(() => { if (!scenario.targets.includes(mission.target)) setMission((current) => ({ ...current, target:scenario.targets[0] })) }, [scenario, mission.target])
  return <div><PageIntro kicker="OpenStreetMap · Shared decision process" title="Common Drone Environment" description="Choose the number of simulated villages, select a specific delivery area, and follow the drone over an interactive OpenStreetMap base layer. Coordinates and demands remain simulated."/>
  <section className="panel-pad"><OpenStreetDroneMap state={state} maxBattery={batteryCapacity} scenario={scenario}/><div className="mt-5 flex flex-wrap gap-2"><button className="btn-primary" onClick={start} disabled={running}><Play size={16}/>Start mission</button><button className="btn-secondary" onClick={step} disabled={running || state.terminal}><SkipForward size={16}/>Next step</button><button className="btn-secondary" onClick={() => setRunning(true)} disabled={running || state.terminal}><Play size={16}/>Auto run</button><button className="btn-secondary" onClick={() => setRunning(false)} disabled={!running}><Pause size={16}/>Pause</button><button className="btn-secondary" onClick={reset}><RotateCcw size={16}/>Reset</button></div></section>
  <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="panel-pad"><h2 className="font-bold">Mission setup</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><label><span className="label">Number of villages</span><input className="field" type="number" min="1" max={MAX_DYNAMIC_VILLAGES} step="1" value={villageCount} disabled={running} onChange={(e) => setVillageCount(Math.max(1,Math.min(MAX_DYNAMIC_VILLAGES,Math.floor(Number(e.target.value)||1))))}/><span className="mt-1 block text-xs text-slate-400">Choose 1–{MAX_DYNAMIC_VILLAGES} villages.</span></label><label><span className="label">Battery health (%)</span><input className="field" type="number" min="0" max="100" step="1" value={resources.batteryHealth} disabled={running} onChange={(e) => setResources((current) => ({ ...current, batteryHealth: Math.max(0, Math.min(100, Number(e.target.value) || 0)) }))}/><span className="mt-1 block text-xs text-slate-400">Enter battery condition from 0% to 100%.</span></label><label><span className="label">Target area</span><select className="field" value={mission.target} onChange={(e) => setMission((m) => ({...m,target:e.target.value}))}>{Object.entries(scenario.areas).map(([village,areas]) => <optgroup key={village} label={`${village} areas`}>{areas.map((area) => <option key={area.id} value={area.id}>{area.label}</option>)}</optgroup>)}</select></label>{[['payload','Payload',['FOOD','MEDICINE','BOTH']],['weather','Initial weather',['SAFE','WINDY','SEVERE']]].map(([key,label,values]) => <label key={key}><span className="label">{label}</span><select className="field" value={mission[key]} onChange={(e) => setMission((m) => ({...m,[key]:e.target.value}))}>{values.map((v) => <option key={v}>{v}</option>)}</select></label>)}</div></section><section className="panel-pad"><h2 className="font-bold">Live outcome</h2><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-slate-50 p-3"><span className="text-xs text-slate-500">Steps</span><strong className="block text-xl">{timeline.length}</strong></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-xs text-slate-500">Total reward</span><strong className="block text-xl">{total}</strong></div></div>{state.terminal && <p className={`mt-3 rounded-lg p-3 text-sm font-semibold ${state.success ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{state.success ? `Delivery completed at ${state.target}.` : 'Mission ended without delivery.'}</p>}</section></div>
  <section className="panel-pad mt-5"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><p className="eyebrow">Current flood context</p><h2 className="mt-1 font-bold">Documented Chattogram localities</h2></div><p className="text-xs text-slate-500">Names and impact notes are sourced; demands and area points are simulated.</p></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{scenario.villages.map((village)=><article key={village.id} className="rounded-xl border border-slate-100 bg-slate-50 p-4"><div className="flex items-start justify-between gap-2"><div><span className="text-xs font-bold text-teal-700">{village.id}</span><h3 className="mt-1 font-bold text-slate-900">{village.name}</h3></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${village.urgency==='Critical'?'bg-rose-100 text-rose-700':'bg-orange-100 text-orange-700'}`}>{village.urgency}</span></div><p className="mt-3 text-xs leading-5 text-slate-600">{village.floodContext}</p><p className="mt-2 text-[10px] text-slate-400">{village.coordinateNote}</p><a className="mt-2 inline-block text-xs font-bold text-teal-700 hover:underline" href={village.sourceUrl} target="_blank" rel="noreferrer">{village.sourceLabel} ↗</a></article>)}</div></section>
  <section className="panel-pad mt-5 overflow-x-auto"><h2 className="font-bold">Mission timeline</h2>{timeline.length === 0 ? <p className="mt-4 text-sm text-slate-500">No transitions yet. Start the mission or select Next Step.</p> : <table className="mt-4 w-full min-w-[760px] text-left text-xs"><thead><tr className="border-b uppercase text-slate-500"><th className="pb-3">Step</th><th>State</th><th>Action</th><th>Result</th><th>Reward</th></tr></thead><tbody>{timeline.map((r) => <tr key={r.step} className="border-b border-slate-100"><td className="py-3">{r.step}</td><td>{r.from}</td><td className="font-bold text-teal-700">{r.action}</td><td>{r.to}</td><td className={r.reward >= 0 ? 'text-emerald-700' : 'text-rose-600'}>{r.reward}</td></tr>)}</tbody></table>}</section></div>
}
