import PageIntro from '../components/common/PageIntro'
import Notice from '../components/common/Notice'
const sections=[
 ['1. Bangladesh flood-relief problem','Seasonal flooding can isolate communities from roads and health facilities. This simulation uses documented flood-affected locality names from southern Chattogram while modeling food, medicine, drones, batteries, and delivery areas with simulated values.'],
 ['2. Why simulated drones?','A drone can model rapid last-mile transport when roads are inaccessible. Real deployment would require aviation approval, verified terrain, trained operators, robust hardware, and coordination with emergency authorities.'],
 ['3. Particle Swarm Optimization','PSO is a population-based numerical search. Each particle is a 16-value allocation: four food quantities, four medicine quantities, four mission counts, and four battery reserves. Continuous positions are rounded and repaired before evaluation.'],
 ['4. Fitness and constraints','The optimizer maximizes fitness = −cost. Cost = 100Cₘ + 40Nₘ + 10Fᵤ + 5T + 3E + 100V + 30G, where terms represent unmet critical and non-critical medicine, unmet food, time, energy, capacity violations, and the village satisfaction gap.'],
 ['5. Shared Markov decision process','Both decision algorithms use state s = (location, battery, payload, target, weather), the same 11 actions, the same reward function, and the same stochastic movement and weather transitions. Transition and reward logic are never duplicated.'],
 ['6. Value Iteration','Value Iteration knows the environment model. It repeatedly applies V(s) = maxₐ Σₛ′ P(s′|s,a)[R + γV(s′)] until the maximum update is below θ, then extracts the maximizing action as its policy.'],
 ['7. Q-Learning','Q-Learning learns through interaction without receiving transition probabilities. Its update is Q(s,a) ← Q(s,a) + α[r + γ maxₐ′Q(s′,a′) − Q(s,a)]. Epsilon-greedy exploration gradually shifts from discovery to exploitation.'],
 ['8. Model-based vs model-free','Value Iteration can be sample-efficient when its explicit probability model is correct, but may weaken under model mismatch. Q-Learning requires many training episodes, yet can adapt from experienced outcomes without a complete model.'],
 ['9. Hyperparameters','PSO behavior depends on swarm size, iterations, inertia, c₁, and c₂. Value Iteration depends on γ and θ. Q-Learning depends on episodes, learning rate α, γ, epsilon, minimum epsilon, and decay. Seeded randomness supports reproducibility.'],
 ['10. Limitations','The graph, battery levels, payload types, villages, rewards, and weather are deliberately simplified. The model omits flight dynamics, exact mass, airspace, communications, human factors, uncertainty in demand, and real geographic data.'],
]
export default function MethodologyPage(){return <div><PageIntro kicker="Academic documentation" title="Problem Formulation & Methodology" description="A plain-language account of the optimization problem, common MDP, learning algorithms, experimental controls, limitations, and ethics."/><Notice>Locality names and flood-impact notes are sourced from published reporting. Demands, delivery areas, resource quantities, weather, rewards, and algorithm outputs remain simulated. This system is not validated for real response or medical decisions.</Notice><div className="mt-6 grid gap-4 lg:grid-cols-2">{sections.map(([title,body])=><section key={title} className="panel-pad"><h2 className="font-bold text-slate-900">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{body}</p></section>)}</div><section className="mt-5 rounded-2xl border border-rose-200 bg-rose-50 p-6"><h2 className="font-bold text-rose-900">Ethical disclaimer</h2><p className="mt-2 text-sm leading-7 text-rose-800">No output should determine who receives food, medicine, or emergency help. Real allocation must be accountable to affected communities and qualified authorities, use verified live information, protect vulnerable people, and include human review. The software provides no medical advice.</p></section></div>}
