import { useState } from 'react'
import { Download, Play, RotateCcw, SlidersHorizontal } from 'lucide-react'
import { useApp } from '../appStore'
import { runPSO } from '../algorithms/pso'
import { defaultPso, defaultResources } from '../data/defaultParameters'
import { defaultVillages } from '../data/villages'
import { getBaselines } from '../simulation/baselines'
import PageIntro from '../components/common/PageIntro'
import ParameterInput from '../components/common/ParameterInput'
import MetricCard from '../components/common/MetricCard'
import { BarPlot, LinePlot } from '../components/charts/BasicCharts'
import { exportCSV, exportJSON } from '../utils/exportResults'
import { chattogramFloodLocalities, MAX_DYNAMIC_VILLAGES } from '../simulation/dynamicVillageNetwork'

const number = (value) => Number(value)
export default function PSOPage() {
  const { villages, setVillages, resources, setResources, results, saveResult } = useApp()
  const [params, setParams] = useState(defaultPso), [error, setError] = useState(''), result = results.pso
  const updateParam = (key, value) => setParams((p) => ({ ...p, [key]: number(value) }))
  const updateVillage = (index, key, value) => setVillages((current) => current.map((v, i) => i === index ? { ...v, [key]: Math.max(0, number(value)) } : v))
  const updateVillageCount = (value) => {
    const count = Math.max(1, Math.min(MAX_DYNAMIC_VILLAGES, Math.floor(number(value) || 1)))
    setVillages((current) => chattogramFloodLocalities.slice(0, count).map((source) => current.find((village) => village.id === source.id) || { ...source }))
    saveResult('pso', null)
  }
  const execute = () => { try { setError(''); saveResult('pso', runPSO({ ...params, villages, resources })) } catch (e) { setError(e.message) } }
  const reset = () => { if (!result || confirm('Reset parameters, data, and the current PSO result?')) { setParams(defaultPso); setVillages(defaultVillages); setResources(defaultResources); saveResult('pso', null) } }
  const baselines = result ? [{ name: 'PSO', ...result }, ...getBaselines(villages, resources, params.seed)] : []
  const allocations = result ? villages.map((v, i) => ({ village: v.id, foodDemand: v.foodDemand, food: result.food[i], medicineDemand: v.medicineDemand, medicine: result.medicine[i], missions: result.missions[i], batteryHealth: result.batteryHealth, satisfaction: result.satisfaction[i] })) : []
  return <div><PageIntro kicker="Part 1 · Optimization" title="PSO Resource Allocation" description="Each particle searches only food and medicine quantities. Mission counts are derived from weighted payload, while battery health is reported as a percentage." actions={<><button className="btn-secondary" onClick={reset}><RotateCcw size={16}/>Reset</button><button className="btn-primary" onClick={execute}><Play size={16}/>Run PSO</button></>}/>
  {error && <div className="mb-4 rounded-xl bg-rose-50 p-3 text-sm font-medium text-rose-700">{error}</div>}
  <div className="grid gap-5 xl:grid-cols-[340px_1fr]"><aside className="space-y-5"><section className="panel-pad"><h2 className="flex items-center gap-2 font-bold"><SlidersHorizontal size={18} className="text-teal-700"/>Algorithm parameters</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-1">{[['swarmSize','Swarm size'],['iterations','Iterations'],['inertia','Inertia weight'],['c1','Cognitive c1'],['c2','Social c2'],['seed','Random seed']].map(([key,label]) => <ParameterInput key={key} label={label} type="number" min={key === 'swarmSize' ? 2 : 0} step={['inertia','c1','c2'].includes(key) ? .1 : 1} value={params[key]} onChange={(e) => updateParam(key,e.target.value)}/>)}</div></section>
  <section className="panel-pad"><h2 className="font-bold">Village scenario</h2><div className="mt-4"><ParameterInput label="Number of villages" hint={`Choose 1–${MAX_DYNAMIC_VILLAGES} documented Chattogram localities`} type="number" min="1" max={MAX_DYNAMIC_VILLAGES} step="1" value={villages.length} onChange={(e) => updateVillageCount(e.target.value)}/></div><div className="mt-4 flex flex-wrap gap-2">{chattogramFloodLocalities.slice(0,villages.length).map((village)=><span key={village.id} className="rounded-lg bg-teal-50 px-2 py-1 text-[10px] font-bold text-teal-700">{village.id} · {village.name}</span>)}</div></section>
  <section className="panel-pad"><h2 className="font-bold">Available resources</h2><div className="mt-4 grid grid-cols-2 gap-3">{[['drones','Drones'],['food','Food'],['medicine','Medicine']].map(([key,label]) => <ParameterInput key={key} label={label} type="number" min={key === 'drones' ? 1 : 0} value={resources[key]} onChange={(e) => setResources((r) => ({ ...r, [key]: Math.max(key === 'drones' ? 1 : 0, Math.floor(number(e.target.value) || 0)) }))}/>) }<ParameterInput label="Battery health (%)" type="number" min="0" max="100" step="1" value={resources.batteryHealth} onChange={(e) => setResources((r) => ({ ...r, batteryHealth: Math.max(0, Math.min(100, number(e.target.value) || 0)) }))}/></div></section></aside>
  <main className="space-y-5"><section className="panel-pad overflow-x-auto"><div className="mb-4"><h2 className="font-bold">Editable village demand</h2><p className="mt-1 text-xs text-slate-500">Non-negative values are enforced before optimization.</p></div><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs uppercase tracking-wider text-slate-500"><th className="pb-3">Village</th><th className="pb-3">Urgency</th><th className="pb-3">Food demand</th><th className="pb-3">Medicine demand</th><th className="pb-3">Distance</th></tr></thead><tbody>{villages.map((v,i) => <tr key={v.id} className="border-b border-slate-100"><td className="py-3 font-semibold">{v.id} · {v.name}</td><td><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{v.urgency}</span></td><td><input aria-label={`${v.id} food demand`} className="field !w-24" type="number" min="0" value={v.foodDemand} onChange={(e) => updateVillage(i,'foodDemand',e.target.value)}/></td><td><input aria-label={`${v.id} medicine demand`} className="field !w-24" type="number" min="0" value={v.medicineDemand} onChange={(e) => updateVillage(i,'medicineDemand',e.target.value)}/></td><td>{v.distance} km</td></tr>)}</tbody></table></section>
  {!result ? <section className="panel-pad flex min-h-56 flex-col items-center justify-center text-center"><span className="rounded-full bg-teal-50 p-4 text-teal-700"><Play/></span><h2 className="mt-4 font-bold">Ready to optimize</h2><p className="mt-2 max-w-md text-sm text-slate-500">Run PSO to calculate a reproducible allocation, convergence history, fairness, and baseline comparison.</p></section> : <Results result={result} allocations={allocations} baselines={baselines}/>}</main></div></div>
}

function Results({ result, allocations, baselines }) {
  return <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Best total cost" value={result.cost.toFixed(1)}/><MetricCard label="Food satisfied" value={`${result.foodSatisfaction.toFixed(1)}%`} tone="blue"/><MetricCard label="Medicine satisfied" value={`${result.medicineSatisfaction.toFixed(1)}%`} tone="rose"/><MetricCard label="Fairness score" value={`${result.fairnessScore.toFixed(1)}%`} tone="amber"/></section>
  <section className="grid gap-5 lg:grid-cols-2"><div className="panel-pad"><div className="flex justify-between"><h2 className="font-bold">Fitness convergence</h2><button className="text-teal-700" title="Export PSO JSON" onClick={() => exportJSON('pso-result.json', result)}><Download size={18}/></button></div><LinePlot data={result.history} xKey="iteration" lines={[{key:'bestFitness',name:'Best fitness'},{key:'averageFitness',name:'Average fitness',color:'#f59e0b'}]}/></div><div className="panel-pad"><h2 className="font-bold">Demand vs allocation</h2><BarPlot data={allocations} xKey="village" bars={[{key:'foodDemand',name:'Food demand',color:'#bae6fd'},{key:'food',name:'Food allocated',color:'#0f766e'}]}/></div></section>
  <section className="panel-pad overflow-x-auto"><div className="flex items-center justify-between"><h2 className="font-bold">Allocation plan</h2><button className="btn-secondary" onClick={() => exportCSV('pso-allocation.csv', allocations)}><Download size={15}/>CSV</button></div><table className="mt-4 w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="pb-3">Village</th><th>Food</th><th>Medicine</th><th>Derived missions</th><th>Battery health</th><th>Satisfaction</th></tr></thead><tbody>{allocations.map((row,i) => <tr key={row.village} className="border-b border-slate-100"><td className="py-3 font-bold">{row.village}</td><td>{result.food[i]}</td><td>{result.medicine[i]}</td><td>{result.missions[i]}</td><td>{result.batteryHealth}%</td><td>{row.satisfaction.toFixed(1)}%</td></tr>)}</tbody></table></section>
  <section className="panel-pad overflow-x-auto"><h2 className="font-bold">Baseline comparison</h2><table className="mt-4 w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="pb-3">Method</th><th>Total cost</th><th>Unmet food</th><th>Unmet medicine</th><th>Fairness</th><th>Energy</th></tr></thead><tbody>{baselines.map((b) => <tr key={b.name} className="border-b border-slate-100"><td className="py-3 font-bold">{b.name}</td><td>{b.cost.toFixed(1)}</td><td>{b.unmetFood}</td><td>{b.unmetMedicine}</td><td>{b.fairnessScore.toFixed(1)}%</td><td>{b.energy.toFixed(1)}</td></tr>)}</tbody></table></section></>
}
