import { useRef, useState } from 'react'
import { Download, Play, Square } from 'lucide-react'
import { useApp } from '../appStore'
import PageIntro from '../components/common/PageIntro'
import ParameterInput from '../components/common/ParameterInput'
import MetricCard from '../components/common/MetricCard'
import { LinePlot } from '../components/charts/BasicCharts'
import { FloodDroneEnvironment } from '../simulation/floodDroneEnvironment'
import { bestQAction, runQLearning } from '../algorithms/qLearning'
import { defaultQl } from '../data/defaultParameters'
import { exportJSON } from '../utils/exportResults'
import { areaTargets } from '../data/network'

const rolling = (history, window = 50) => history.map((row,i) => { const chunk=history.slice(Math.max(0,i-window+1),i+1); return {...row,rollingReward:chunk.reduce((s,r)=>s+r.reward,0)/chunk.length,rollingSuccess:chunk.reduce((s,r)=>s+r.success,0)/chunk.length*100} })
export default function QLearningPage() {
  const { villages, resources, results, saveResult } = useApp(), [params,setParams] = useState(defaultQl), [running,setRunning] = useState(false), [error,setError] = useState(''), cancelRef=useRef(false), [selected,setSelected]=useState({target:'V3-A1',payload:'MEDICINE',weather:'WINDY',battery:resources.batteryCapacity})
  const result=results.ql
  const train=()=>{ setRunning(true);setError('');cancelRef.current=false;setTimeout(()=>{if(cancelRef.current)return setRunning(false);try{const env=new FloodDroneEnvironment({villages,seed:params.seed,maxSteps:params.maxSteps,maxBattery:resources.batteryCapacity});saveResult('ql',{...runQLearning(env,params),maxBattery:resources.batteryCapacity})}catch(e){setError(e.message)}finally{setRunning(false)}},30) }
  const stop=()=>{cancelRef.current=true;setRunning(false)}
  const env=new FloodDroneEnvironment({villages,maxBattery:resources.batteryCapacity}), state={location:'H',...selected,battery:Math.min(selected.battery,resources.batteryCapacity)}, best=result?bestQAction(result.qTable,env,state):null, stateKey=env.encodeState(state), chart=result?rolling(result.history):[], batteryValues=Array.from({length:resources.batteryCapacity},(_,index)=>index+1)
  return <div><PageIntro kicker="Part 2B · Model-free learning" title="Q-Learning Experiment" description="Train an epsilon-greedy tabular agent through sampled interactions with the same FloodDroneEnvironment used by Value Iteration." actions={<><button className="btn-secondary" disabled={!result} onClick={()=>exportJSON('q-learning-summary.json',result)}><Download size={16}/>Export</button>{running?<button className="btn-secondary !text-rose-700" onClick={stop}><Square size={16}/>Cancel training</button>:<button className="btn-primary" onClick={train}><Play size={16}/>Train agent</button>}</>}/>
  {error&&<div className="mb-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<div className="grid gap-5 xl:grid-cols-[330px_1fr]"><aside className="space-y-5"><section className="panel-pad"><h2 className="font-bold">Training parameters</h2><div className="mt-4 space-y-4">{[['episodes','Episodes',1],['alpha','Alpha (α)',.01],['gamma','Gamma (γ)',.01],['epsilon','Initial epsilon',.01],['minEpsilon','Minimum epsilon',.01],['epsilonDecay','Epsilon decay',.0001],['maxSteps','Maximum steps',1],['seed','Random seed',1]].map(([key,label,step])=><ParameterInput key={key} label={label} type="number" min="0" step={step} value={params[key]} onChange={(e)=>setParams({...params,[key]:Number(e.target.value)})}/>)}</div></section><section className="panel-pad"><h2 className="font-bold">Inspect learned state</h2><div className="mt-4 space-y-3">{[['target',areaTargets],['payload',['FOOD','MEDICINE','BOTH']],['weather',['SAFE','WINDY','SEVERE']],['battery',batteryValues]].map(([field,values])=><label key={field}><span className="label">{field}</span><select className="field" value={field==='battery'?Math.min(selected[field],resources.batteryCapacity):selected[field]} onChange={(e)=>setSelected({...selected,[field]:field==='battery'?Number(e.target.value):e.target.value})}>{values.map(v=><option key={v}>{v}</option>)}</select></label>)}</div><div className="mt-4 rounded-xl bg-teal-50 p-4"><span className="text-xs font-semibold text-teal-700">Best learned action</span><strong className="mt-1 block text-xl">{best||'Train agent'}</strong></div></section></aside>
  <main className="space-y-5">{running&&<div className="panel-pad"><div className="flex items-center gap-3"><span className="h-5 w-5 animate-spin rounded-full border-2 border-teal-600 border-t-transparent"/><div><strong className="text-sm">Training sampled episodes…</strong><p className="text-xs text-slate-500">State-action values are being updated from real environment transitions.</p></div></div></div>}{!result?<div className="panel-pad flex min-h-72 items-center justify-center text-center text-sm text-slate-500">Train the agent to populate its Q-table and learning curves.</div>:<><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Success rate" value={`${result.successRate.toFixed(1)}%`}/><MetricCard label="Average reward" value={result.averageReward.toFixed(1)} tone="blue"/><MetricCard label="Final epsilon" value={result.finalEpsilon.toFixed(3)} tone="amber"/><MetricCard label="Learned Q-values" value={result.qTable.size.toLocaleString()} tone="rose"/></section><section className="grid gap-5 lg:grid-cols-2"><div className="panel-pad"><h2 className="font-bold">Reward learning curve</h2><LinePlot data={chart.filter((_,i)=>i%Math.max(1,Math.floor(chart.length/300))===0)} xKey="episode" lines={[{key:'reward',name:'Episode reward',color:'#94a3b8'},{key:'rollingReward',name:'Rolling average'}]}/></div><div className="panel-pad"><h2 className="font-bold">Success rate over time</h2><LinePlot data={chart.filter((_,i)=>i%Math.max(1,Math.floor(chart.length/300))===0)} xKey="episode" lines={[{key:'rollingSuccess',name:'Rolling success %',color:'#2563eb'}]}/></div></section><section className="grid gap-5 lg:grid-cols-2"><div className="panel-pad"><h2 className="font-bold">Training summary</h2><dl className="mt-4 space-y-3 text-sm">{[['Episodes completed',result.episodes],['Runtime',`${result.runtime.toFixed(1)} ms`],['Average steps',result.averageSteps.toFixed(2)],['Battery failure rate',`${result.batteryFailureRate.toFixed(1)}%`],['Critical medicine success',`${result.criticalSuccessRate.toFixed(1)}%`]].map(([l,v])=><div key={l} className="flex justify-between border-b border-slate-100 pb-3"><dt className="text-slate-500">{l}</dt><dd className="font-bold">{v}</dd></div>)}</dl></div><div className="panel-pad"><h2 className="font-bold">Q-values for selected state</h2><p className="mt-1 break-all text-xs text-slate-400">{stateKey}</p><div className="mt-4 space-y-2">{env.getValidActions(state).map(action=>{const value=result.qTable.get(`${stateKey}::${action}`)||0;return <div key={action} className={`flex justify-between rounded-lg p-2 text-sm ${action===best?'bg-teal-50 text-teal-800':'bg-slate-50'}`}><span>{action}</span><strong>{value.toFixed(2)}</strong></div>})}</div></div></section></>}</main></div></div>
}
